baydamafish_app:
    resource: "@BaydamafishAppBundle/Resources/config/routing.yml"
    prefix:   /

baydamafish_product:
    resource: "@BaydamafishProductBundle/Resources/config/routing.yml"
    prefix:   /product


